# Generated by Django 5.1.7 on 2025-08-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0002_project_timesheetentry_weeksummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='timesheet_app.project'),
        ),
    ]
