# Generated by Django 5.1.7 on 2025-08-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0003_alter_timesheetentry_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
