# Generated by Django 5.1.7 on 2025-08-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0004_alter_timesheetentry_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
