# Generated by Django 5.1.7 on 2025-08-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0005_alter_timesheetentry_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeksummary',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
